openapi: 3.0.0
info:
  title: User
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:8080/api
  variables: {}
paths:
  /users:
    get:
      tags:
      - Misc
      summary: getAllUser
      operationId: getAllUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Misc
      summary: createUser
      operationId: createUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/createUserRequest'
              - example:
                  name: loc minh
                  password: '123456'
                  birthday: 19/05/2000
                  gender: Female
                  email: tuanloc123@gmail.com
                  phone: '0938110045'
                  role: CLIENT
            example:
              name: loc minh
              password: '123456'
              birthday: 19/05/2000
              gender: Female
              email: tuanloc123@gmail.com
              phone: '0938110045'
              role: CLIENT
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/3:
    get:
      tags:
      - Misc
      summary: getUserById
      operationId: getUserById
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Misc
      summary: deleteUser
      operationId: deleteUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/search/minh:
    get:
      tags:
      - Misc
      summary: getUserBySearchName
      operationId: getUserBySearchName
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/getUserPagination/pageIndex=2/pageSize=3:
    get:
      tags:
      - Misc
      summary: getUserPagination
      operationId: getUserPagination
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/4:
    put:
      tags:
      - Misc
      summary: updateUserById
      operationId: updateUserById
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/updateUserByIdRequest'
              - example:
                  name: MinhToan
                  password: duy171900
                  birthday: 19/05/2000
                  gender: Female
                  phone: '0938110045'
                  role: CLIENT
            example:
              name: MinhToan
              password: duy171900
              birthday: 19/05/2000
              gender: Female
              phone: '0938110045'
              role: CLIENT
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    createUserRequest:
      title: createUserRequest
      required:
      - name
      - password
      - birthday
      - gender
      - email
      - phone
      - role
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
        gender:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
      example:
        name: loc minh
        password: '123456'
        birthday: 19/05/2000
        gender: Female
        email: tuanloc123@gmail.com
        phone: '0938110045'
        role: CLIENT
    uploadAvatarRequest:
      title: uploadAvatarRequest
      required:
      - name
      - password
      - birthday
      - gender
      - email
      - phone
      - role
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
        gender:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
      example:
        name: loc minh
        password: '123456'
        birthday: 19/05/2000
        gender: Female
        email: tuanloc123@gmail.com
        phone: '0938110045'
        role: CLIENT
    updateUserByIdRequest:
      title: updateUserByIdRequest
      required:
      - name
      - password
      - birthday
      - gender
      - phone
      - role
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
        gender:
          type: string
        phone:
          type: string
        role:
          type: string
      example:
        name: MinhToan
        password: duy171900
        birthday: 19/05/2000
        gender: Female
        phone: '0938110045'
        role: CLIENT
    deleteUserRequest:
      title: deleteUserRequest
      required:
      - name
      - password
      - birthday
      - gender
      - phone
      - role
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        birthday:
          type: string
        gender:
          type: string
        phone:
          type: string
        role:
          type: string
      example:
        name: MinhToan
        password: duy171900
        birthday: 19/05/2000
        gender: Female
        phone: '0938110045'
        role: CLIENT
tags:
- name: Misc
  description: ''
